#include <iostream>
#include "PE3_stock.h"
using std::cout;
using std::endl;
int main(int argc, char const *argv[])
{
    Stock mystuff[4] = {
        {"NanoSmart", 12, 20.0},
        {"Boffo Objects", 200, 2.0},
        {"Monolithic Obelisks", 130, 3.25},
        {"Fleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep Enterprises", 60, 6.5}};
    cout << mystuff[0] << '\n';
    Stock stocks[10] = {
        {"NanoSmart", 12, 20.0},
        Stock(),
        Stock("Boffo Objects", 200, 2.0),
        Stock("Fleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep EnterprisesFleep Enterprises")};

    for (int i = 0; i < 10; i++)
    {
        cout << stocks[i] << endl;
    }
    return 0;
}
